name: Deploy to VPS

on:
  push:
    branches: [master, main]
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increase timeout for build process

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "🚀 Starting deployment via GitHub Actions..."
            
            # Navigate to project directory
            cd /root/crysgarage-deploy
            
            # Pull latest changes
            echo "📥 Pulling latest changes..."
            git pull origin master
            
            # Frontend: Build and deploy
            echo "🌐 Building frontend..."
            cd crysgarage-frontend
            
            # Clean install dependencies
            echo "📦 Installing dependencies..."
            rm -rf node_modules package-lock.json
            npm ci
            
            # Build frontend
            echo "🔨 Building frontend..."
            npm run build
            
            # Verify build output
            echo "✅ Verifying build output..."
            if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
              echo "❌ Frontend build failed - dist directory or index.html not found"
              exit 1
            fi
            
            # Copy built files to web root with verification
            echo "📁 Copying files to web root..."
            rm -rf /var/www/html/*
            cp -r dist/* /var/www/html/
            
            # Verify files were copied
            if [ ! -f "/var/www/html/index.html" ]; then
              echo "❌ Files not copied to web root"
              exit 1
            fi
            
            # Fix permissions
            echo "🔐 Setting permissions..."
            chown -R nginx:nginx /var/www/html/
            chmod -R 755 /var/www/html/
            restorecon -Rv /var/www/html/
            
            # Backend: Update and restart
            echo "🔧 Updating backend..."
            cd ../crysgarage-backend
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            systemctl restart crysgarage-backend
            
            # Ruby service: Update and restart
            echo "💎 Updating Ruby service..."
            cd ../crysgarage-ruby
            gem install bundler:2.6.7 || echo "Bundler version issue - continuing..."
            bundle install
            systemctl restart crysgarage-ruby
            
            # Reload Nginx
            echo "🌐 Reloading Nginx..."
            nginx -t && systemctl reload nginx
            
            # Health check with retries
            echo "🏥 Running health check..."
            for i in {1..5}; do
              sleep 5
              if curl -f -s https://crysgarage.studio > /dev/null; then
                echo "✅ GitHub Actions deployment successful!"
                echo "🌐 Site is live at: https://crysgarage.studio"
                exit 0
              else
                echo "⏳ Health check attempt $i failed, retrying..."
              fi
            done
            
            echo "❌ Health check failed after 5 attempts"
            exit 1
