name: Deploy to VPS

on:
  push:
    branches: [master, main]
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increase timeout for build process

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "🚀 Starting deployment via GitHub Actions..."
            
            # Navigate to project directory
            cd /root/crysgarage-deploy
            
            # Pull latest changes
            git pull origin master
            
            # Frontend: Build and deploy
            echo "Building frontend..."
            cd crysgarage-frontend
            npm ci
            npm run build
            
            # Copy built files to web root
            rm -rf /var/www/html/*
            cp -r dist/* /var/www/html/
            restorecon -Rv /var/www/html
            
            # Backend: Update and restart
            echo "Updating backend..."
            cd ../crysgarage-backend
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            systemctl restart crysgarage-backend
            
            # Ruby service: Update and restart
            echo "Updating Ruby service..."
            cd ../crysgarage-ruby
            gem install bundler:2.6.7 || echo "Bundler version issue - continuing..."
            bundle install
            systemctl restart crysgarage-ruby
            
            # Reload Nginx
            echo "Reloading Nginx..."
            nginx -t && systemctl reload nginx
            
            # Health check
            echo "Running health check..."
            sleep 5
            if curl -f https://crysgarage.studio > /dev/null; then
              echo "✅ GitHub Actions deployment successful!"
            else
              echo "❌ GitHub Actions deployment failed!"
              exit 1
            fi
