name: Deploy to VPS

on:
  push:
    branches: [master, main]
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increase timeout for build process

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "🚀 Starting deployment via GitHub Actions..."
            
            # Set environment variables for better memory management
            export NODE_OPTIONS="--max-old-space-size=2048"
            export DOCKER_BUILDKIT=1
            export COMPOSE_DOCKER_CLI_BUILD=1
            
            # Navigate to deployment directory
            cd /var/www/crysgarage-deploy
            
            # Make sure the deployment script is executable
            chmod +x deploy_vps_simple.sh
            
            # Run the enhanced deployment script
            ./deploy_vps_simple.sh
            
            # Additional verification
            echo "🔍 Verifying deployment..."
            if curl -s -f https://crysgarage.studio > /dev/null; then
              echo "✅ GitHub Actions deployment successful!"
            else
              echo "❌ GitHub Actions deployment failed!"
              exit 1
            fi
